DROP TABLE IF EXISTS bettor CASCADE;
DROP TABLE IF EXISTS suggestion CASCADE;
DROP TABLE IF EXISTS team CASCADE;
DROP TABLE IF EXISTS matchup CASCADE;
DROP TABLE IF EXISTS matchup_team CASCADE;
DROP TABLE IF EXISTS wager CASCADE;
